// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xssntonzfpgnexrvahnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc250b256ZnBnbmV4cnZhaG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzYzNDYsImV4cCI6MjA2MzExMjM0Nn0.G0bg9DjjA_zraK8r1FBoHquqtK8IKPgF10MO380HViM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);